### ISSUE TITLE
Spanish language is replaced by duplicate Basque language

### ISSUE THREAD

**Issue by huizache** [CityZenApp/AndroidApp#106]
Cityzen in spanish shows in basque. In
https://github.com/CityZenApp/Android-Development/tree/master/CityZenApp/app/src/main/res

I see there are two basque languages values:
values-eu  Added translation using Weblate (Basque), commited 2 years ago and with proper basque "eu" iso language code

and

values-es-rEU Translated using Weblate (Basque), commited 10 months ago with an iso code I cannot find, but with "es-" for spanish

I am pretty sure this is the problem

**Comment by kominoshja** [comment]
@huizache Thank you for opening this issue! Can you confirm that 
[`CityZenApp/app/src/main/res/values-es-rEU/strings.xml`](https://github.com/CityZenApp/Android-Development/blob/master/CityZenApp/app/src/main/res/values-es-rEU/strings.xml) is in Basque? If so we can move the content of that file over at [`CityZenApp/app/src/main/res/values-eu/strings.xml`](https://github.com/CityZenApp/Android-Development/blob/master/CityZenApp/app/src/main/res/values-eu/strings.xml), which would then allow [`CityZenApp/app/src/main/res/values-es/strings.xml`](https://github.com/CityZenApp/Android-Development/blob/master/CityZenApp/app/src/main/res/values-es/strings.xml) to load properly, since there won't be an `es-rEu` to confuse the code

**Comment by huizache** [comment]
@kominoshja it is in Basque, but I am not a basque speaker, so am not cualified to comment on quality of the translation.

What I did notice scan reading the es-rEu string is that it skips lines and misses a few words and phrases, thus giving the menu partialy in spanish for example.

I also scan read the eu string and it does not skip lines.

I would not recomend mixing es-rEu string with eu string until a Basque speaker reviews them. But removing the "es" from es-rEu does seem the right step.

**Comment by kominoshja** [comment]
@huizache I confirmed that https://github.com/CityZenApp/Android-Development/commit/4e97b4895acc55ec3904ba0b2940472c2322c84c fixes the issue. Please check so we can push to master

[app-debug.apk](https://git.collective68.tech/CityZen/106-patch/-/jobs/1211/artifacts/raw/app/build/outputs/apk/debug/app-debug.apk)

**Comment by huizache** [comment]
@kominoshja [4e97b48](https://github.com/CityZenApp/AndroidApp/commit/4e97b4895acc55ec3904ba0b2940472c2322c84c) is the basque translation. I cannot comment on basque translation. It is the proper basque ISO language code "values-eu".

**Comment by kominoshja** [comment]
Perfect. Merging tonight
